package langs

var Countries = map[string]string{
	"AD": "Andorra",
	"AE": "Emirados Árabes Unidos",
	"AF": "Afeganistão",
	"AG": "Antígua e Barbuda",
	"AI": "Anguila",
	"AL": "Albânia",
	"AM": "Arménia",
	"AO": "Angola",
	"AQ": "Antártida",
	"AR": "Argentina",
	"AS": "Samoa Americana",
	"AT": "Áustria",
	"AU": "Austrália",
	"AW": "Aruba",
	"AX": "Ilhas Åland",
	"AZ": "Azerbaijão",
	"BA": "Bósnia-Herzegovina",
	"BB": "Barbados",
	"BD": "Bangladesh",
	"BE": "Bélgica",
	"BF": "Burkina Faso",
	"BG": "Bulgária",
	"BH": "Bahrein",
	"BI": "Burundi",
	"BJ": "Benim",
	"BL": "São Bartolomeu",
	"BM": "Bermudas",
	"BN": "Brunei",
	"BO": "Bolívia",
	"BQ": "Países Baixos Caribenhos",
	"BR": "Brasil",
	"BS": "Bahamas",
	"BT": "Butão",
	"BV": "Ilha Bouvet",
	"BW": "Botsuana",
	"BY": "Bielorrússia",
	"BZ": "Belize",
	"CA": "Canadá",
	"CC": "Ilhas Cocos (Keeling)",
	"CD": "República Popular do Congo",
	"CF": "República Centro-Africana",
	"CG": "República Democrática do Congo",
	"CH": "Suíça",
	"CI": "Costa do Marfim",
	"CK": "Ilhas Cook",
	"CL": "Chile",
	"CM": "Camarões",
	"CN": "China",
	"CO": "Colômbia",
	"CR": "Costa Rica",
	"CU": "Cuba",
	"CV": "Cabo Verde",
	"CW": "Curaçao",
	"CX": "Ilha de Natal",
	"CY": "Chipre",
	"CZ": "Chéquia",
	"DE": "Alemanha",
	"DJ": "Djibouti",
	"DK": "Dinamarca",
	"DM": "Dominica",
	"DO": "República Dominicana",
	"DZ": "Argélia",
	"EC": "Equador",
	"EE": "Estónia",
	"EG": "Egito",
	"EH": "Saara Ocidental",
	"ER": "Eritreia",
	"ES": "Espanha",
	"ET": "Etiópia",
	"FI": "Finlândia",
	"FJ": "Fiji",
	"FK": "Ilhas Malvinas",
	"FM": "Micronésia",
	"FO": "Ilhas Faroé",
	"FR": "França",
	"GA": "Gabão",
	"GB": "Reino Unido",
	"GD": "Granada",
	"GE": "Geórgia",
	"GF": "Guiana Francesa",
	"GG": "Guernsey",
	"GH": "Gana",
	"GI": "Gibraltar",
	"GL": "Gronelândia",
	"GM": "Gâmbia",
	"GN": "Guiné",
	"GP": "Guadalupe",
	"GQ": "Guiné Equatorial",
	"GR": "Grécia",
	"GS": "Geórgia do Sul e Ilhas Sandwich do Sul",
	"GT": "Guatemala",
	"GU": "Guam",
	"GW": "Guiné-Bissau",
	"GY": "Guiana",
	"HK": "Hong Kong",
	"HM": "Ilha Heard e Ilhas McDonald",
	"HN": "Honduras",
	"HR": "Croácia",
	"HT": "Haiti",
	"HU": "Hungria",
	"ID": "Indonésia",
	"IE": "Irlanda",
	"IL": "Israel",
	"IM": "Ilha de Man",
	"IN": "Índia",
	"IO": "Território Britânico do Oceano Índico",
	"IQ": "Iraque",
	"IR": "Irão",
	"IS": "Islândia",
	"IT": "Itália",
	"JE": "Jersey",
	"JM": "Jamaica",
	"JO": "Jordânia",
	"JP": "Japão",
	"KE": "Quénia",
	"KG": "Quirguistão",
	"KH": "Camboja",
	"KI": "Quiribati",
	"KM": "Comores",
	"KN": "São Cristóvão e Neves",
	"KP": "Coreia do Norte",
	"KR": "Coreia do Sul",
	"KW": "Koweit",
	"KY": "Ilhas Caimão",
	"KZ": "Cazaquistão",
	"LA": "Laos",
	"LB": "Líbano",
	"LC": "Santa Lúcia",
	"LI": "Liechtenstein",
	"LK": "Sri Lanka",
	"LR": "Libéria",
	"LS": "Lesoto",
	"LT": "Lituânia",
	"LU": "Luxemburgo",
	"LV": "Letónia",
	"LY": "Líbia",
	"MA": "Marrocos",
	"MC": "Mónaco",
	"MD": "Moldávia",
	"ME": "Montenegro",
	"MF": "São Martinho",
	"MG": "Madagáscar",
	"MH": "Ilhas Marshall",
	"MK": "Macedónia do Norte",
	"ML": "Mali",
	"MM": "Mianmar (Birmânia)",
	"MN": "Mongólia",
	"MO": "Macau",
	"MP": "Ilhas Marianas do Norte",
	"MQ": "Martinica",
	"MR": "Mauritânia",
	"MS": "Monserrate",
	"MT": "Malta",
	"MU": "Maurícia",
	"MV": "Maldivas",
	"MW": "Maláui",
	"MX": "México",
	"MY": "Malásia",
	"MZ": "Moçambique",
	"NA": "Namíbia",
	"NC": "Nova Caledónia",
	"NE": "Níger",
	"NF": "Ilha Norfolk",
	"NG": "Nigéria",
	"NI": "Nicarágua",
	"NL": "Países Baixos",
	"NO": "Noruega",
	"NP": "Nepal",
	"NR": "Nauru",
	"NU": "Niue",
	"NZ": "Nova Zelândia",
	"OM": "Omã",
	"PA": "Panamá",
	"PE": "Peru",
	"PF": "Polinésia Francesa",
	"PG": "Papua-Nova Guiné",
	"PH": "Filipinas",
	"PK": "Paquistão",
	"PL": "Polónia",
	"PM": "Saint Pierre e Miquelon",
	"PN": "Ilhas Pitcairn",
	"PR": "Porto Rico",
	"PS": "Territórios palestinos",
	"PT": "Portugal",
	"PW": "Palau",
	"PY": "Paraguai",
	"QA": "Qatar",
	"RE": "Reunião",
	"RO": "Roménia",
	"RS": "Sérvia",
	"RU": "Rússia",
	"RW": "Ruanda",
	"SA": "Arábia Saudita",
	"SB": "Ilhas Salomão",
	"SC": "Seychelles",
	"SD": "Sudão",
	"SE": "Suécia",
	"SG": "Singapura",
	"SH": "Santa Helena",
	"SI": "Eslovénia",
	"SJ": "Svalbard e Jan Mayen",
	"SK": "Eslováquia",
	"SL": "Serra Leoa",
	"SM": "San Marino",
	"SN": "Senegal",
	"SO": "Somália",
	"SR": "Suriname",
	"SS": "Sudão do Sul",
	"ST": "São Tomé e Príncipe",
	"SV": "El Salvador",
	"SY": "Síria",
	"SZ": "Essuatíni",
	"TC": "Ilhas Turcas e Caicos",
	"TD": "Chade",
	"TF": "Terras Austrais e Antárticas Francesas",
	"TG": "Togo",
	"TH": "Tailândia",
	"TJ": "Tajiquistão",
	"TK": "Tokelau",
	"TL": "Timor-Leste",
	"TM": "Turquemenistão",
	"TN": "Tunísia",
	"TO": "Tonga",
	"TR": "Turquia",
	"TT": "Trindade e Tobago",
	"TV": "Tuvalu",
	"TW": "Taiwan",
	"TZ": "Tanzânia",
	"UA": "Ucrânia",
	"UG": "Uganda",
	"UM": "Ilhas Distantes dos EUA",
	"US": "Estados Unidos da América",
	"UY": "Uruguai",
	"UZ": "Uzbequistão",
	"VA": "Santa Sé",
	"VC": "São Vicente e Granadinas",
	"VE": "Venezuela",
	"VG": "Ilhas Virgens Britânicas",
	"VI": "Ilhas Virgens Americanas",
	"VN": "Vietname",
	"VU": "Vanuatu",
	"WF": "Wallis e Futuna",
	"WS": "Samoa",
	"XK": "Kosovo",
	"YE": "Iémen",
	"YT": "Mayotte",
	"ZA": "África do Sul",
	"ZM": "Zâmbia",
	"ZW": "Zimbábue",
}
